// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqp5tcdXRMEZiuApihWSYseO-bgRnBJ2o',
    appId: '1:89380618199:web:41ccd7c1960f94894c9592',
    messagingSenderId: '89380618199',
    projectId: 'mis-lab-5c2a9',
    authDomain: 'mis-lab-5c2a9.firebaseapp.com',
    storageBucket: 'mis-lab-5c2a9.appspot.com',
    measurementId: 'G-0T4HZ2SQ98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsKleRQmCVynagXtxUctSUycHEgLtBRos',
    appId: '1:89380618199:android:e421f045e2b829334c9592',
    messagingSenderId: '89380618199',
    projectId: 'mis-lab-5c2a9',
    storageBucket: 'mis-lab-5c2a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4NIfc6424-TlaKKqQz66jHiSC667lmKw',
    appId: '1:89380618199:ios:75f8b2fe992ddf644c9592',
    messagingSenderId: '89380618199',
    projectId: 'mis-lab-5c2a9',
    storageBucket: 'mis-lab-5c2a9.appspot.com',
    iosBundleId: 'com.example.lab3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4NIfc6424-TlaKKqQz66jHiSC667lmKw',
    appId: '1:89380618199:ios:d8d813909fd349f84c9592',
    messagingSenderId: '89380618199',
    projectId: 'mis-lab-5c2a9',
    storageBucket: 'mis-lab-5c2a9.appspot.com',
    iosBundleId: 'com.example.lab3.RunnerTests',
  );
}
